# Site settings
title: JellyGGumi Growth Diary
email: "banggujin@gmail.com"
description: "Photo is memory"
url: "https://jellyggumi.github.io"
baseurl: "/"
naver_username: "jelly_ggumi"
youtube_username: "jelly_ggumi"
facebook_username: ""
twitter_username: ""
instagram_username: "jelly._.ggumi"
github_username:  "jellyggumi"
deviantart_username: ""
flickr_username: ""
discus_shortname: ""
share: true

# Owner/author information
owner:
  name: jelly_ggumi
  avatar: INA.png
  favicon: favicon.ico
  info: Jelly GGumi Blog

plugins:
  - jekyll-sitemap

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
nav:
  - GALLERY: "https://jellyggumi.github.io/gallery/"  
  - JOURNAL: "https://jellyggumi.github.io/journal/"
  - ABOUT: "https://jellyggumi.github.io/about/"
  - PRIVACY: "https://jellyggumi.github.io/privacy/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000

google_site_verification: mfV0-xbtMeYnOR_RUx43PwdtFtWH5HlaJ7xFxITxyRA
# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-include-cache
 - jekyll-gist
 - jekyll-analytics
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
